// Generates test/objdump_fixture.txt out of the binaries of this machine.
//
// Each line of the fixture is '<bytes in hex> <mnemonic>', taken from the
// output of objdump -d, e.g.:
//   4883ec08 sub
// Run it with `make fixture` from the root of the repository.
'use strict';
const child_process = require('child_process');
const fs = require('fs');

// The binaries to disassemble. /bin/ls and libc give the everyday integer
// code, libcrypto gives the SSE / AVX / AVX-512 one.
const SOURCES = [
  '/bin/ls',
  '/usr/lib/x86_64-linux-gnu/libc.so.6',
  '/usr/lib/x86_64-linux-gnu/libcrypto.so.3',
];
// How many cases to keep per mnemonic and per source. Without a cap the
// fixture would be a few hundred thousand 'mov' and 'endbr64'.
const CASES_PER_MNEMONIC = 8;

// The words which objdump prints in front of the mnemonic itself, e.g. the
// 'bnd' of 'bnd jmp' or the 'rex.WRB' of 'rex.WRB stos'.
const PREFIX_WORD_PATTERN =
    /^(lock|rep|repz|repnz|repe|repne|bnd|notrack|data16|addr32|rex(\.[wrxb]+)?|cs|ds|es|fs|gs|ss|xacquire|xrelease)$/;

function disassemble(path) {
  return child_process
      .execSync(`objdump -d ${path}`, {
        maxBuffer: 1024 * 1024 * 1024,
        encoding: 'utf8',
      })
      .split('\n');
}

// Reads the '  4004:\t48 83 ec 08          \tsub    $0x8,%rsp' lines of
// objdump, joining the continuation lines of the instructions which are too
// long to be printed on one line.
function parseObjdumpOutput(lines) {
  const cases = [];
  for (const line of lines) {
    const m =
        line.match(/^\s*[0-9a-f]+:\t([0-9a-f]{2}(?: [0-9a-f]{2})*)\s*(.*)$/);
    if (!m)
      continue;
    const bytes = m[1].replace(/ /g, '');
    const text = m[2].trim();
    if (text === '') {
      // A continuation line: it belongs to the instruction above it.
      if (cases.length !== 0)
        cases[cases.length - 1].bytes += bytes;
      continue;
    }
    cases.push({bytes: bytes, text: text});
  }
  return cases;
}

function mnemonicOf(text) {
  const words = text.split(/\s+/);
  for (const w of words) {
    const word = w.toLowerCase();
    if (PREFIX_WORD_PATTERN.test(word))
      continue;
    return word;
  }
  return '';
}

function main() {
  const outPath = process.argv[2];
  if (!outPath) {
    console.error('usage: node gen_objdump_fixture.js <output path>');
    process.exit(1);
  }
  const objdumpVersion =
      child_process.execSync('objdump --version').toString().split('\n')[0];
  const seen = {};
  const out = [];
  for (const source of SOURCES) {
    if (!fs.existsSync(source)) {
      console.error(`skipping ${source}: not found`);
      continue;
    }
    const perMnemonic = {};
    let kept = 0;
    for (const c of parseObjdumpOutput(disassemble(source))) {
      if (c.text.indexOf('(bad)') !== -1)
        continue;
      const mnemonic = mnemonicOf(c.text);
      if (mnemonic === '' || !mnemonic.match(/^[a-z][a-z0-9._]*$/))
        continue;
      if (seen[c.bytes])
        continue;
      if ((perMnemonic[mnemonic] | 0) >= CASES_PER_MNEMONIC)
        continue;
      seen[c.bytes] = true;
      perMnemonic[mnemonic] = (perMnemonic[mnemonic] | 0) + 1;
      kept++;
      out.push(`${c.bytes} ${mnemonic}`);
    }
    console.log(`${source}: ${kept} cases`);
  }
  const header = [
    '# Cases for test/decoder_test.js, generated by `make fixture`.',
    '# Each line is: <instruction bytes in hex> <mnemonic printed by objdump>',
    `# ${objdumpVersion}`,
    `# sources: ${SOURCES.join(' ')}`,
    `# at most ${CASES_PER_MNEMONIC} cases per mnemonic and per source`,
  ];
  fs.writeFileSync(outPath, header.concat(out).join('\n') + '\n');
  console.log(`wrote ${out.length} cases to ${outPath}`);
}

main();
